/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    DeleteOutlined: typeof import('@ant-design/icons-vue')['DeleteOutlined']
    DoubleLeftOutlined: typeof import('@ant-design/icons-vue')['DoubleLeftOutlined']
    DoubleRightOutlined: typeof import('@ant-design/icons-vue')['DoubleRightOutlined']
    EditOutlined: typeof import('@ant-design/icons-vue')['EditOutlined']
    FilterOutlined: typeof import('@ant-design/icons-vue')['FilterOutlined']
    FolderOpenOutlined: typeof import('@ant-design/icons-vue')['FolderOpenOutlined']
    FolderOutlined: typeof import('@ant-design/icons-vue')['FolderOutlined']
    PlusOutlined: typeof import('@ant-design/icons-vue')['PlusOutlined']
    RedoOutlined: typeof import('@ant-design/icons-vue')['RedoOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchOutlined: typeof import('@ant-design/icons-vue')['SearchOutlined']
  }
}
